Add pod labels to helm chart, add relabeling rule
banzaicloud/kafka-minion-helm-chart pull request #3
Opened 2020-08-17 16:09 UTC by hi-im-aren

.

2020-08-17 16:31 UTC, stoader commented on kafka-minion/templates/servicemonitor.yaml
> +    {{ toYaml .Values.serviceMonitor.relabelings | indent 4 }}
I think it's safer to use `ident 6`

2020-08-17 16:33 UTC, stoader requested changes

2020-08-17 16:33 UTC, stoader commented on kafka-minion/values.yaml
> +  - sourceLabels: [__meta_kubernetes_pod_label_kafka_cr]
I wouldn't add this to the default values yaml, but rather provide these settings from Supertubes.

2020-08-17 17:18 UTC, stoader approved these changes

2020-08-18 07:23 UTC, baluchicken approved these changes

2020-08-18 09:14 UTC, merged